baseurl = "https://thomasdezeeuw.nl"
languageCode = "en-us"
title = "Thomas de Zeeuw"
theme = "Cactus"

disableHugoGeneratorInject = true
disableKinds = [ "taxonomy", "term", "RSS", "sitemap", "robotsTXT" ]

[permalinks]
  post = "/blog/:year/:month/:day/:slug"

[params]
  name = "Thomas de Zeeuw"
  bio = "Software enthusiast"
  # Links in the header.
  links = [
  	["GitHub page", "https://github.com/Thomasdezeeuw"],
  	#["Go notes", "/notes/go"],
  ]
  # RSS feed link.
  enableRSS = false
  # Copyright message in the footer.
  copyright = "© Copyright 2015-2022 Thomas de Zeeuw"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "solarized-light"
    tabWidth = 4
