baseurl = "thomasdezeeuw.nl"
languageCode = "en-us"
title = "Thomas de Zeeuw"
theme = "Cactus"

[permalinks]
  post = "/blog/:year/:month/:day/:slug"

[params]
  name = "Thomas de Zeeuw"
  bio = "Software enthusiast"

  # RSS feed.
  enableRSS = true
  # Links in the header.
  links = [
  	["Go notes", "/notes/go"],
  	["GitHub page", "https://github.com/thomasdezeeuw"],
  ]


  # copyright message in the footer.
  copyright = "© Copyright 2015 Thomas de Zeeuw"
